-- DAYOFF DATABASE FIX + COMPLETE SETUP
-- Run all of this in Supabase Dashboard > SQL Editor.

create table if not exists public.profiles(
 id uuid primary key references auth.users(id) on delete cascade,
 username text unique not null, full_name text, avatar_url text, bio text default '',
 last_seen timestamptz default now(), created_at timestamptz default now()
);
alter table public.profiles enable row level security;
drop policy if exists "profiles_select" on public.profiles;
drop policy if exists "profiles_insert" on public.profiles;
drop policy if exists "profiles_update" on public.profiles;
create policy "profiles_select" on public.profiles for select using(true);
create policy "profiles_insert" on public.profiles for insert to authenticated with check(auth.uid()=id);
create policy "profiles_update" on public.profiles for update to authenticated using(auth.uid()=id) with check(auth.uid()=id);

create or replace function public.handle_new_user() returns trigger
language plpgsql security definer set search_path=public as $$
begin
 insert into public.profiles(id,username,full_name)
 values(new.id,coalesce(new.raw_user_meta_data->>'username','user_'||substr(new.id::text,1,8)),new.raw_user_meta_data->>'full_name')
 on conflict(id) do nothing;
 return new;
end $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

-- THIS FIXES: "Could not find the table public.posts in the schema cache"
create table if not exists public.posts(
 id bigint generated by default as identity primary key,
 user_id uuid not null references public.profiles(id) on delete cascade,
 content text, media_url text, media_type text, created_at timestamptz default now()
);
alter table public.posts add column if not exists media_url text;
alter table public.posts add column if not exists media_type text;
alter table public.posts alter column content drop not null;
alter table public.posts enable row level security;
drop policy if exists "posts_select" on public.posts;
drop policy if exists "posts_insert" on public.posts;
drop policy if exists "posts_update" on public.posts;
drop policy if exists "posts_delete" on public.posts;
create policy "posts_select" on public.posts for select using(true);
-- THIS FIXES: "new row violates row-level security policy"
create policy "posts_insert" on public.posts for insert to authenticated with check(auth.uid()=user_id);
create policy "posts_update" on public.posts for update to authenticated using(auth.uid()=user_id) with check(auth.uid()=user_id);
create policy "posts_delete" on public.posts for delete to authenticated using(auth.uid()=user_id);

create table if not exists public.post_likes(
 post_id bigint references public.posts(id) on delete cascade,
 user_id uuid references public.profiles(id) on delete cascade,
 created_at timestamptz default now(), primary key(post_id,user_id)
);
alter table public.post_likes enable row level security;
drop policy if exists "likes_select" on public.post_likes;
drop policy if exists "likes_insert" on public.post_likes;
drop policy if exists "likes_delete" on public.post_likes;
create policy "likes_select" on public.post_likes for select using(true);
create policy "likes_insert" on public.post_likes for insert to authenticated with check(auth.uid()=user_id);
create policy "likes_delete" on public.post_likes for delete to authenticated using(auth.uid()=user_id);

create table if not exists public.comments(
 id bigint generated by default as identity primary key,
 post_id bigint references public.posts(id) on delete cascade,
 user_id uuid references public.profiles(id) on delete cascade,
 content text not null, created_at timestamptz default now()
);
alter table public.comments enable row level security;
drop policy if exists "comments_select" on public.comments;
drop policy if exists "comments_insert" on public.comments;
drop policy if exists "comments_update" on public.comments;
drop policy if exists "comments_delete" on public.comments;
create policy "comments_select" on public.comments for select using(true);
create policy "comments_insert" on public.comments for insert to authenticated with check(auth.uid()=user_id);
create policy "comments_update" on public.comments for update to authenticated using(auth.uid()=user_id) with check(auth.uid()=user_id);
create policy "comments_delete" on public.comments for delete to authenticated using(auth.uid()=user_id);

create table if not exists public.follows(
 follower_id uuid references public.profiles(id) on delete cascade,
 following_id uuid references public.profiles(id) on delete cascade,
 status text not null default 'pending',
 created_at timestamptz default now(),
 primary key(follower_id,following_id),
 check(follower_id<>following_id),
 check(status in('pending','accepted','rejected'))
);
alter table public.follows enable row level security;
drop policy if exists "follows_select" on public.follows;
drop policy if exists "follows_insert" on public.follows;
drop policy if exists "follows_update" on public.follows;
drop policy if exists "follows_delete" on public.follows;
create policy "follows_select" on public.follows for select using(status='accepted' or follower_id=auth.uid() or following_id=auth.uid());
create policy "follows_insert" on public.follows for insert to authenticated with check(auth.uid()=follower_id);
create policy "follows_update" on public.follows for update to authenticated using(auth.uid()=following_id) with check(auth.uid()=following_id);
create policy "follows_delete" on public.follows for delete to authenticated using(auth.uid()=follower_id or auth.uid()=following_id);

create table if not exists public.notifications(
 id bigint generated by default as identity primary key,
 user_id uuid references public.profiles(id) on delete cascade,
 actor_id uuid references public.profiles(id) on delete cascade,
 type text not null, post_id bigint references public.posts(id) on delete cascade,
 created_at timestamptz default now(), read boolean default false
);
alter table public.notifications enable row level security;
drop policy if exists "notifications_select" on public.notifications;
drop policy if exists "notifications_insert" on public.notifications;
drop policy if exists "notifications_update" on public.notifications;
create policy "notifications_select" on public.notifications for select to authenticated using(auth.uid()=user_id);
create policy "notifications_insert" on public.notifications for insert to authenticated with check(auth.uid()=actor_id);
create policy "notifications_update" on public.notifications for update to authenticated using(auth.uid()=user_id) with check(auth.uid()=user_id);

create table if not exists public.messages(
 id bigint generated by default as identity primary key,
 sender_id uuid references public.profiles(id) on delete cascade,
 receiver_id uuid references public.profiles(id) on delete cascade,
 content text not null, created_at timestamptz default now(), read boolean default false
);
alter table public.messages enable row level security;
drop policy if exists "messages_select" on public.messages;
drop policy if exists "messages_insert" on public.messages;
drop policy if exists "messages_update" on public.messages;
drop policy if exists "messages_delete" on public.messages;
create policy "messages_select" on public.messages for select to authenticated using(auth.uid()=sender_id or auth.uid()=receiver_id);
create policy "messages_insert" on public.messages for insert to authenticated with check(auth.uid()=sender_id);
create policy "messages_update" on public.messages for update to authenticated using(auth.uid()=receiver_id) with check(auth.uid()=receiver_id);
create policy "messages_delete" on public.messages for delete to authenticated using(auth.uid()=sender_id);

insert into storage.buckets(id,name,public) values('post-media','post-media',true)
on conflict(id) do update set public=true;

drop policy if exists "media_read" on storage.objects;
drop policy if exists "media_insert" on storage.objects;
drop policy if exists "media_delete" on storage.objects;
create policy "media_read" on storage.objects for select using(bucket_id='post-media');
create policy "media_insert" on storage.objects for insert to authenticated
with check(bucket_id='post-media' and (storage.foldername(name))[1]=auth.uid()::text);
create policy "media_delete" on storage.objects for delete to authenticated
using(bucket_id='post-media' and owner_id=auth.uid()::text);

do $$
begin
 begin alter publication supabase_realtime add table public.messages;
 exception when duplicate_object then null; end;
end $$;
-- DAYOFF REAL LIVE BROADCASTING (WebRTC + Supabase Realtime signaling)
-- Run this AFTER your existing Dayoff SQL.

create extension if not exists pgcrypto;

create table if not exists public.live_sessions (
  id uuid primary key default gen_random_uuid(),
  host_id uuid not null references public.profiles(id) on delete cascade,
  title text not null default 'Dayoff Live',
  status text not null default 'live' check (status in ('live','ended')),
  created_at timestamptz not null default now(),
  last_heartbeat timestamptz not null default now(),
  ended_at timestamptz
);

create unique index if not exists one_active_live_per_host
on public.live_sessions(host_id)
where status = 'live';

alter table public.live_sessions enable row level security;

drop policy if exists "Anyone can view live sessions" on public.live_sessions;
create policy "Anyone can view live sessions"
on public.live_sessions for select
using (true);

drop policy if exists "Users can start their own live" on public.live_sessions;
create policy "Users can start their own live"
on public.live_sessions for insert
to authenticated
with check (auth.uid() = host_id);

drop policy if exists "Hosts can update their live" on public.live_sessions;
create policy "Hosts can update their live"
on public.live_sessions for update
to authenticated
using (auth.uid() = host_id)
with check (auth.uid() = host_id);

drop policy if exists "Hosts can delete their live" on public.live_sessions;
create policy "Hosts can delete their live"
on public.live_sessions for delete
to authenticated
using (auth.uid() = host_id);

create table if not exists public.live_signals (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.live_sessions(id) on delete cascade,
  from_user uuid not null references public.profiles(id) on delete cascade,
  to_user uuid not null references public.profiles(id) on delete cascade,
  type text not null check (type in ('offer','answer','ice','leave')),
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists live_signals_to_user_idx on public.live_signals(to_user, created_at);
create index if not exists live_signals_session_idx on public.live_signals(session_id, created_at);

alter table public.live_signals enable row level security;

drop policy if exists "Users can read their live signals" on public.live_signals;
create policy "Users can read their live signals"
on public.live_signals for select
to authenticated
using (auth.uid() = from_user or auth.uid() = to_user);

drop policy if exists "Users can send their live signals" on public.live_signals;
create policy "Users can send their live signals"
on public.live_signals for insert
to authenticated
with check (auth.uid() = from_user);

drop policy if exists "Users can delete their live signals" on public.live_signals;
create policy "Users can delete their live signals"
on public.live_signals for delete
to authenticated
using (auth.uid() = from_user);

-- Optional live comments/chat during broadcasts.
create table if not exists public.live_comments (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.live_sessions(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  content text not null check (length(trim(content)) between 1 and 500),
  created_at timestamptz not null default now()
);

create index if not exists live_comments_session_idx on public.live_comments(session_id, created_at);
alter table public.live_comments enable row level security;

drop policy if exists "Anyone can read live comments" on public.live_comments;
create policy "Anyone can read live comments"
on public.live_comments for select
using (true);

drop policy if exists "Users can send live comments" on public.live_comments;
create policy "Users can send live comments"
on public.live_comments for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users can delete their live comments" on public.live_comments;
create policy "Users can delete their live comments"
on public.live_comments for delete
to authenticated
using (auth.uid() = user_id);

-- Enable Supabase Realtime for signaling and live discovery.
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'live_signals'
  ) then
    execute 'alter publication supabase_realtime add table public.live_signals';
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'live_sessions'
  ) then
    execute 'alter publication supabase_realtime add table public.live_sessions';
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'live_comments'
  ) then
    execute 'alter publication supabase_realtime add table public.live_comments';
  end if;
end $$;

-- Quick check after running the SQL:
select id, host_id, title, status, created_at, last_heartbeat
from public.live_sessions
order by created_at desc
limit 10;
