-- DAYOFF REAL LIVE BROADCASTING (WebRTC + Supabase Realtime signaling)
-- Run this AFTER your existing Dayoff SQL.

create extension if not exists pgcrypto;

create table if not exists public.live_sessions (
  id uuid primary key default gen_random_uuid(),
  host_id uuid not null references public.profiles(id) on delete cascade,
  title text not null default 'Dayoff Live',
  status text not null default 'live' check (status in ('live','ended')),
  created_at timestamptz not null default now(),
  last_heartbeat timestamptz not null default now(),
  ended_at timestamptz
);

create unique index if not exists one_active_live_per_host
on public.live_sessions(host_id)
where status = 'live';

alter table public.live_sessions enable row level security;

drop policy if exists "Anyone can view live sessions" on public.live_sessions;
create policy "Anyone can view live sessions"
on public.live_sessions for select
using (true);

drop policy if exists "Users can start their own live" on public.live_sessions;
create policy "Users can start their own live"
on public.live_sessions for insert
to authenticated
with check (auth.uid() = host_id);

drop policy if exists "Hosts can update their live" on public.live_sessions;
create policy "Hosts can update their live"
on public.live_sessions for update
to authenticated
using (auth.uid() = host_id)
with check (auth.uid() = host_id);

drop policy if exists "Hosts can delete their live" on public.live_sessions;
create policy "Hosts can delete their live"
on public.live_sessions for delete
to authenticated
using (auth.uid() = host_id);

create table if not exists public.live_signals (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.live_sessions(id) on delete cascade,
  from_user uuid not null references public.profiles(id) on delete cascade,
  to_user uuid not null references public.profiles(id) on delete cascade,
  type text not null check (type in ('offer','answer','ice','leave')),
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists live_signals_to_user_idx on public.live_signals(to_user, created_at);
create index if not exists live_signals_session_idx on public.live_signals(session_id, created_at);

alter table public.live_signals enable row level security;

drop policy if exists "Users can read their live signals" on public.live_signals;
create policy "Users can read their live signals"
on public.live_signals for select
to authenticated
using (auth.uid() = from_user or auth.uid() = to_user);

drop policy if exists "Users can send their live signals" on public.live_signals;
create policy "Users can send their live signals"
on public.live_signals for insert
to authenticated
with check (auth.uid() = from_user);

drop policy if exists "Users can delete their live signals" on public.live_signals;
create policy "Users can delete their live signals"
on public.live_signals for delete
to authenticated
using (auth.uid() = from_user);

-- Optional live comments/chat during broadcasts.
create table if not exists public.live_comments (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.live_sessions(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  content text not null check (length(trim(content)) between 1 and 500),
  created_at timestamptz not null default now()
);

create index if not exists live_comments_session_idx on public.live_comments(session_id, created_at);
alter table public.live_comments enable row level security;

drop policy if exists "Anyone can read live comments" on public.live_comments;
create policy "Anyone can read live comments"
on public.live_comments for select
using (true);

drop policy if exists "Users can send live comments" on public.live_comments;
create policy "Users can send live comments"
on public.live_comments for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users can delete their live comments" on public.live_comments;
create policy "Users can delete their live comments"
on public.live_comments for delete
to authenticated
using (auth.uid() = user_id);

-- Enable Supabase Realtime for signaling and live discovery.
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'live_signals'
  ) then
    execute 'alter publication supabase_realtime add table public.live_signals';
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'live_sessions'
  ) then
    execute 'alter publication supabase_realtime add table public.live_sessions';
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'live_comments'
  ) then
    execute 'alter publication supabase_realtime add table public.live_comments';
  end if;
end $$;

-- Quick check after running the SQL:
select id, host_id, title, status, created_at, last_heartbeat
from public.live_sessions
order by created_at desc
limit 10;
